name: r2s_lean_minimal

on:
  #push:
  #  branches:
  #    - master
  #  paths:
  #    - '.github/workflows/r2s_lean_minimal.yml'
  #schedule:
  #  - cron: '10 08 * * *'
  #watch:
  #  types: [started]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler  g++-multilib antlr3 gperf wget swig
          curl https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh  | sed '/#/d' | sed 's/\\//g' | sed 's/exit 0//g' | sed 's/sudo apt -y install//g' | sed 's/sudo apt-get -y install//g' | sed 's/:i386//g' | xargs sudo apt-get -y --no-install-recommends install
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /usr/local/share/boost /opt/ghc

      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Init Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle --depth=1
          repo sync -c --no-tags --no-clone-bundle -j8
          cd friendlywrt/ && git fetch --unshallow

      - name: Patch Kernel
        run: |
          . patch_kernel_5.4.sh

      - name: Mods
        run: |
          cd friendlywrt-rk3328
          . ../remove_unused_config.sh
          cat configs/config_rk3328 | grep "TARGET" >> ../base_rk3328.seed
          cat ../base_rk3328.seed > configs/config_rk3328
          echo '
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_OPENSSL_ENGINE_BUILTIN=y
          CONFIG_OPENSSL_WITH_DTLS=y
          CONFIG_OPENSSL_WITH_EC2M=y
          CONFIG_OPENSSL_WITH_NPN=y
          CONFIG_PACKAGE_autocore=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_diffutils=y
          CONFIG_PACKAGE_vim-fuller=y
          CONFIG_PACKAGE_pv=y
          CONFIG_PACKAGE_pigz=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_losetup=y
          CONFIG_LIBSODIUM_MINIMAL=y
          CONFIG_LUCI_LANG_zh-cn=y
          # CONFIG_LUCI_LANG_en is not set
          # CONFIG_LUCI_LANG_zh-tw is not set
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          # CONFIG_PACKAGE_luci-theme-argon is not set
          # CONFIG_PACKAGE_luci-theme-material is not set
          # CONFIG_PACKAGE_luci-theme-netgear is not set
          CONFIG_PACKAGE_ddns-scripts_aliyun=y
          CONFIG_PACKAGE_ddns-scripts_cloudflare.com-v4=y
          CONFIG_PACKAGE_kmod-rtl8xxxu=y
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          # CONFIG_PACKAGE_luci-app-adguardhome is not set
          # CONFIG_PACKAGE_luci-app-airplay2 is not set
          # CONFIG_PACKAGE_luci-app-amule is not set
          CONFIG_PACKAGE_luci-app-arpbind=y
          # CONFIG_PACKAGE_luci-app-autoreboot is not set
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-filetransfer=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-flowoffload=y
          # CONFIG_PACKAGE_luci-app-frpc is not set
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          # CONFIG_PACKAGE_luci-app-ipsec-vpnserver-manyusers is not set
          # CONFIG_PACKAGE_luci-app-koolproxyR is not set
          # CONFIG_PACKAGE_luci-app-music-remote-center is not set
          CONFIG_PACKAGE_luci-app-mwan3=y
          # CONFIG_PACKAGE_luci-app-netdata is not set
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          # CONFIG_PACKAGE_luci-app-openvpn-server is not set
          # CONFIG_PACKAGE_luci-app-passwall is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Brook is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ChinaDNS_NG is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_GO is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_dns2socks is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_haproxy is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ipt2socks is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_kcptun is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_pdnsd is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_simple-obfs is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_v2ray-plugin is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_fuse-utils is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
          # CONFIG_PACKAGE_luci-app-qbittorrent is not set
          CONFIG_PACKAGE_luci-app-r2sflasher=y
          CONFIG_PACKAGE_luci-app-ramfree=y
          # CONFIG_PACKAGE_luci-app-samba is not set
          # CONFIG_PACKAGE_luci-app-sfe is not set
          # CONFIG_PACKAGE_luci-app-sqm is not set
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-uhttpd is not set
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          # CONFIG_PACKAGE_luci-app-webadmin is not set
          # CONFIG_PACKAGE_luci-app-wol is not set
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          # CONFIG_PACKAGE_luci-app-zerotier is not set
          # CONFIG_PACKAGE_luci-app-vssr is not set
          # CONFIG_PACKAGE_luci-app-vssr_INCLUDE_ShadowsocksR_Socks is not set
          # CONFIG_PACKAGE_luci-app-pppoe-relay is not set
          # CONFIG_PACKAGE_luci-app-pppoe-server is not set
          # CONFIG_PACKAGE_luci-app-pptp-vpnserver-manyusers is not set
          # CONFIG_PACKAGE_luci-app-ssr-python-pro-server is not set
          # CONFIG_PACKAGE_luci-app-v2ray-server is not set
          # CONFIG_TARGET_ROOTFS_TARGZ is not set
          # CONFIG_OPENSSL_ENGINE_BUILTIN_DEVCRYPTO is not set
          # CONFIG_PACKAGE_kmod-crypto-authenc is not set
          # CONFIG_PACKAGE_kmod-cryptodev is not set
          # CONFIG_PACKAGE_libopenssl-devcrypto is not set
          # CONFIG_V2RAY_COMPRESS_UPX is not set
          ' >> configs/config_rk3328
          cd friendlywrt
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git remote add upstream https://github.com/coolsnowwolf/lede && git fetch upstream
          git checkout upstream/master -b tmp
          git checkout 33f7cb735300bd9a099995236ed768c8925fec75 -- target/linux/sunxi/image/
          git rm README.md
          git commit -m 'reset'
          git checkout origin/master-v19.07.1
          git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto tmp -X theirs
          rm -rf package/kernel/mt76/Makefile package/network/services/hostapd package/kernel/mac80211
          git checkout d1f2153ca49b5e071c9c29de85bd321b7ce04f95 -- package/kernel/mt76/Makefile package/network/services/hostapd package/kernel/mac80211
          rm target/linux/rockchip-rk3328/patches-4.14/0001-net-thunderx-workaround-BGX-TX-Underflow-issue.patch target/linux/generic/hack-4.14/999-net-patch-linux-kernel-to-support-shortcut-fe.patch
          sed -i '/ipv6/,+3d' package/base-files/files/root/setup.sh
          git checkout upstream/master -- feeds.conf.default
          sed -i -E 's/#(src-git.+)(helloworld.+)/\1\2/' feeds.conf.default
          #cd package/lean/
          #git clone https://github.com/jerrykuku/lua-maxminddb.git
          #git clone https://github.com/jerrykuku/luci-app-vssr.git
          #cd luci-app-vssr/root/etc/
          #echo 'china_ssr.txt
          #config/black.list
          #config/white.list
          #dnsmasq.oversea/oversea_list.conf
          #dnsmasq.ssr/ad.conf
          #dnsmasq.ssr/gfw_base.conf' | xargs rm
          #cd ../../../
          #rm -rf luci-theme-argon
          #git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
          #cd ../../
          git apply ../../enable_autocore.diff
          #git apply ../../fix_cpufreq.diff
          sed -i 's/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/root::0:0:99999:7:::/g' package/lean/default-settings/files/zzz-default-settings
          sed -i 's/ucidef_set_interfaces_lan_wan "eth1" "eth0"/ucidef_set_interfaces_lan_wan "eth0" "eth1"/' target/linux/rockchip-rk3328/base-files/etc/board.d/02_network
          sed -i '/uci commit luci/i\uci set luci.main.mediaurlbase="/luci-static/argon"' package/lean/default-settings/files/zzz-default-settings
          sed -i '/exit/i\chown -R root:root /usr/share/netdata/web' package/lean/default-settings/files/zzz-default-settings
          sed -i '/exit/i\find /etc/rc.d/ -name *docker* -delete' package/lean/default-settings/files/zzz-default-settings
          sed -i 's/option fullcone\t1/option fullcone\t0/' package/network/config/firewall/files/firewall.config
          sed -i '/8.8.8.8/d' package/base-files/files/root/setup.sh
          mv ../../scripts/check_wan4.sh package/base-files/files/usr/bin && sed -i '/exit/i\/bin/sh /usr/bin/check_wan4.sh &' package/base-files/files/etc/rc.local
          mv ../../scripts/autoupdate.sh package/base-files/files/root/au.sh && chmod +x package/base-files/files/root/au.sh

      - name: Update & Install feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add package
        run: |
          cd friendlywrt-rk3328/friendlywrt/package
          git clone https://github.com/Lienol/openwrt-package.git
          mv openwrt-package/lienol/luci-app-passwall/ ./lean
          git clone https://github.com/songchenwen/nanopi-r2s.git
          mv nanopi-r2s/luci-app-r2sflasher/ ./lean
          rm -rf nanopi-r2s/
          git clone https://github.com/project-openwrt/luci-app-koolproxyR.git
          mv luci-app-koolproxyR/ ./lean
          git clone https://github.com/rufengsuixing/luci-app-adguardhome.git
          mv luci-app-adguardhome/ ./lean
      #    git clone https://github.com/garypang13/luci-app-eqos.git
      #    mv luci-app-eqos/ ./lean
      #    git clone https://github.com/vernesong/OpenClash.git
      #    mv OpenClash/luci-app-openclash/ ./lean
      #    rm -rf OpenClash/
      #    git clone https://github.com/frainzy1477/luci-app-clash.git
      #    mv luci-app-clash/ ./lean

      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk

      - name: Zip Files
        run: |
          gzip friendlywrt-rk3328/out/*.img

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp friendlywrt-rk3328/out/*img* ./artifact/
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/
          cd ./artifact/
          md5sum *img* > md5sum.txt
          cd ..
          zip -r artifact.zip ./artifact/
          release_tag="R2S_lean_minimal-$(date +%Y-%m-%d)"
          echo "##[set-output name=release_tag;]$release_tag"

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R2S
          path: ./artifact/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ywt114 }}
        with:
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          release_name: 自动发布 ${{ steps.assemble_artifact.outputs.release_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ywt114 }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./artifact.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM.zip
          asset_content_type: application/zip
